import openingScreen from "./openingScreen/openingScreen";
import logIn from "./logIn/logIn";
import darkMode from "./darkMode/darkMode";
import lightMode from "./lightMode/lightMode";
import backButton from "./backButton/backButton";
import checkingForThumbOMeterFeature from "./featureMenu/checkingThumb/checkThumb";
import checkingForHandFeature from "./featureMenu/checkingHand/checkHand";
import checkingForQuizFeature from "./featureMenu/checkingQuiz/checkQuiz";
import checkingForDjDeck from "./featureMenu/checkingDj/checkDj";
import speakerThumbSession from "./speaker/speakerThumb/speakerThumb";
import speakerStopThumbSession from "./speaker/speakerThumb/speakerThumbSessionStop";

openingScreen();
logIn("speakerview@gmail.com", "(callbackCats)");
darkMode();
// lightMode();
// darkMode();
checkingForThumbOMeterFeature();
// backButton();
speakerThumbSession("Question", 100);
speakerStopThumbSession();
// checkingForHandFeature();
// backButton();
// checkingForQuizFeature();
// backButton();
// checkingForDjDeck();
// backButton();
